"""
This module defines the AppState class, which holds the shared state 
of the ECG application.

Updated project conditions:
    - 6 ECG derivations (generated by analog circuit with CD4051 MUX)
    - Only ESP32 (no Arduino)
    - Manual and Automatic derivation control
"""

import threading
import time
from collections import deque
import tkinter as tk
from . import config


class AppState:

    def __init__(self):

        # =====================================================
        # ---------------- DATA BUFFERS -----------------------
        # =====================================================

        self.data_lock = threading.Lock()

        self.voltage_buffer = deque(maxlen=config.MAX_BUFFER_SIZE)
        self.time_buffer = deque(maxlen=config.MAX_BUFFER_SIZE)
        self.sample_count = 0

        # =====================================================
        # --------------- CONNECTION STATUS -------------------
        # =====================================================

        self.esp32_connected = False

        # =====================================================
        # --------------- DERIVATION CONTROL ------------------
        # =====================================================

        # 6 derivations generated by analog hardware
        self.mux_state_label = {
            0: "I",
            1: "II",
            2: "III",
            3: "aVR",
            4: "aVL",
            5: "aVF"
        }

        self.current_mux_state = 0
        self.mux_lock = threading.Lock()

        # =====================================================
        # ----------- MANUAL / AUTO CONTROL MODE -------------
        # =====================================================

        self.operation_mode = tk.StringVar(value=config.MODE_MANUAL)
        
        # Control de tiempo para auto-switch
        self.last_manual_action_time = time.time()
        self.last_auto_switch_time = time.time()

        # =====================================================
        # -------- UI VARIABLES (AFFECT PROCESSING) -----------
        # =====================================================
        
        self.ecg_gain = tk.DoubleVar(value=config.DEFAULT_GAIN)
        self.window_size = tk.IntVar(value=config.DEFAULT_WINDOW_SIZE)
        self.y_max = tk.DoubleVar(value=config.DEFAULT_Y_MAX)

        self.r_threshold = tk.DoubleVar(value=config.DEFAULT_R_THRESHOLD)
        self.r_distance = tk.IntVar(value=config.DEFAULT_R_DISTANCE)

    # =========================================================
    # ---------------- SIGNAL ACCESS ---------------------------
    # =========================================================

    def get_current_signal(self):
        """
        Returns current ECG signal (already analog from MUX)
        """
        return list(self.voltage_buffer)

    # =========================================================
    # ---------------- MUX CONTROL -----------------------------
    # =========================================================

    def set_mux_state(self, state):
        """
        Sets derivation manually and updates mode to MANUAL
        """
        with self.mux_lock:
            self.current_mux_state = state
            self.operation_mode.set(config.MODE_MANUAL)
            self.last_manual_action_time = time.time()

    def next_derivation(self):
        """
        Moves to next derivation (used for automatic mode)
        """
        with self.mux_lock:
            self.current_mux_state = (self.current_mux_state + 1) % config.TOTAL_DERIVATIONS

    # =========================================================
    # ---------------- AUTO MODE LOGIC -------------------------
    # =========================================================

    def check_auto_mode(self):
        """
        If no manual interaction for AUTO_SWITCH_INTERVAL seconds,
        switch to AUTO mode.
        """

        if time.time() - self.last_manual_action_time > config.AUTO_TIMEOUT:
            self.operation_mode.set(config.MODE_AUTO)

    def auto_switch_if_needed(self):
        """
        Switch derivation every AUTO_SWITCH_INTERVAL seconds
        while in AUTO mode.
        """

        if time.time() - self.last_auto_switch_time > config.AUTO_SWITCH_INTERVAL:
            self.next_derivation()
            self.last_auto_switch_time = time.time()